timePeriods = {'Intertrial Interval', ...
    'Fixation', ...
    'Rule Stimulus', ...
    'Stimulus Response', ...
    'Saccade', ...
    'Reward', ...
    };
modelName = {'Rule + Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    };
%%
factorsOfInterest = {'Previous Error History', 'Rule Repetition', 'Congruency'};
plotCompareDemandByBrainAreas(modelName, timePeriods, factorsOfInterest)
%%
factorsOfInterest = {'Rule'};
plotCompareDemandByBrainAreas(modelName, timePeriods, factorsOfInterest, 'isAbs', true)
%%
modelName = {'Rule * Previous Error History + Rule * Rule Repetition', ...
    'Rule * Previous Error History + Rule * Rule Repetition', ...
    'Rule * Previous Error History + Rule * Rule Repetition', ...
    'Rule * Previous Error History + Rule * Rule Repetition + Congruency + Response Direction', ...
    'Rule * Previous Error History + Rule * Rule Repetition + Congruency + Response Direction', ...
    'Rule * Previous Error History + Rule * Rule Repetition + Congruency + Response Direction', ...
    };

factorsOfInterest = {'Rule:Previous Error History', 'Rule:Rule Repetition'};
plotCompareDemandByBrainAreas(modelName, timePeriods, factorsOfInterest, 'isAbs', true)