clear variables;
ccColor = [102,194,165] / 255;
isaColor = [117,112,179] / 255;

timePeriods = {'Intertrial Interval', ...
    'Fixation', ...
    'Rule Stimulus', ...
    'Stimulus Response', ...
    'Saccade', ...
    'Reward', ...
    };
modelName = {'Rule + Previous Error History', ...
    'Rule + Previous Error History', ...
    'Rule + Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    };

for time_ind = 1:length(timePeriods),
    
    f = figure;
    plotEstByBrainArea(modelName{time_ind}, timePeriods{time_ind}, 'subject', 'cc', 'colors', ccColor)
    plotEstByBrainArea(modelName{time_ind}, timePeriods{time_ind}, 'subject', 'isa', 'colors', isaColor)
    f.Name = timePeriods{time_ind};
    
    f = figure;
    plotEstByBrainArea(modelName{time_ind}, timePeriods{time_ind})
    f.Name = timePeriods{time_ind};
    
end