timePeriods = {'Intertrial Interval', ...
    'Fixation', ...
    'Rule Stimulus', ...
    'Stimulus Response', ...
    'Saccade', ...
    'Reward', ...
    };
modelName = {'Rule + Previous Error History', ...
    'Rule + Previous Error History', ...
    'Rule + Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    };

plotEstByBrainAreaOverTime(modelName, timePeriods)