clear variables;

predType = 'AUC';
timePeriod = 'Rule Stimulus';
models = {...
    'Rule', ...
    'Previous Error History', ...
    'Rule Repetition', ...
    'Rule + Previous Error History', ...
    'Rule + Rule Repetition', ...
    'Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Rule Repetition', ...
    'Rule * Previous Error History + Rule Repetition', ...
    'Previous Error History + Rule * Rule Repetition', ...
    'Rule * Previous Error History + Rule * Rule Repetition', ...
    };

plotPredComb(models, timePeriod, 'brainArea', 'ACC', 'predType', predType)
plotPredComb(models, timePeriod, 'brainArea', 'dlPFC', 'predType', predType)

%%
timePeriod = 'Stimulus Response';
models = {...
    'Rule', ...
    'Previous Error History', ...
    'Rule Repetition', ...
    'Congruency', ...
    'Rule + Previous Error History', ...
    'Rule + Rule Repetition', ...
    'Rule + Congruency', ...
    'Previous Error History + Rule Repetition', ...
    'Previous Error History + Congruency', ...
    'Rule Repetition + Congruency', ...
    'Rule + Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Congruency', ...
    'Previous Error History + Rule Repetition + Congruency', ...
    'Rule + Previous Error History + Rule Repetition + Congruency', ...
    'Rule * Previous Error History', ...
    'Rule * Rule Repetition', ...
    'Rule * Previous Error History + Rule Repetition', ...
    'Previous Error History + Rule * Rule Repetition', ...
    'Rule * Previous Error History + Rule * Rule Repetition', ...
    'Rule * Previous Error History + Congruency', ...
    'Rule * Rule Repetition + Congruency', ...
    'Rule * Previous Error History + Rule Repetition + Congruency', ...
    'Previous Error History + Rule * Rule Repetition + Congruency', ...
    'Rule * Previous Error History + Rule * Rule Repetition + Congruency', ...
    };

plotPredComb(models, timePeriod, 'brainArea', 'ACC')
plotPredComb(models, timePeriod, 'brainArea', 'dlPFC')
