clear variables;

predType = 'AUC';
timePeriod = 'Rule Stimulus';
models = {...
    'Rule', ...
    'Previous Error History', ...
    'Rule Repetition', ...
    'Rule + Previous Error History', ...
    'Rule + Rule Repetition', ...
    'Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Rule Repetition', ...
    };

plotPredComb(models, timePeriod, 'brainArea', 'ACC', 'predType', predType)
plotPredComb(models, timePeriod, 'brainArea', 'dlPFC', 'predType', predType)

%%

timePeriod = 'Stimulus Response';
models = {...
    'Rule', ...
    'Previous Error History', ...
    'Rule Repetition', ...
    'Congruency', ...
    'Response Direction', ...
    'Rule + Previous Error History', ...
    'Rule + Rule Repetition', ...
    'Rule + Congruency', ...
    'Rule + Response Direction', ...
    'Previous Error History + Rule Repetition', ...
    'Previous Error History + Congruency', ...
    'Previous Error History + Response Direction', ...
    'Rule Repetition + Congruency', ...
    'Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition', ...
    'Rule + Previous Error History + Congruency', ...
    'Rule + Previous Error History + Response Direction', ...
    'Rule + Rule Repetition + Response Direction', ...
    'Rule + Congruency + Response Direction', ...
    'Previous Error History + Rule Repetition + Congruency', ...
    'Previous Error History + Rule Repetition + Response Direction', ...
    'Previous Error History + Congruency + Response Direction', ...
    'Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Response Direction', ...
    'Rule + Previous Error History + Congruency + Response Direction', ...
    'Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    'Rule + Previous Error History + Rule Repetition + Congruency', ...
    'Rule + Previous Error History + Rule Repetition + Congruency + Response Direction', ...
    };

plotPredComb(models, timePeriod, 'brainArea', 'ACC')
plotPredComb(models, timePeriod, 'brainArea', 'dlPFC')
