clear variables;
numSim = 1000;
numSamples = [];
overwrite = false;
timePeriods = {'Rule Response', 'Stimulus Reward'};
walltime = '24:00:00';
mem = '80GB';
numCores = 12;
model = {...
    'Previous Error + Response Direction', ...
    'Previous Error + Response Direction + Rule Repetition + Congruency', ...
    'Previous Error + Response Direction + Rule', ...
    'Previous Error + Response Direction + Rule Repetition + Rule', ...
    'Previous Error + Response Direction + Congruency + Rule', ...
    'Previous Error + Response Direction + Rule Repetition + Congruency + Rule', ...
    'Rule * Previous Error + Response Direction', ...
    'Rule * Previous Error + Response Direction + Rule * Rule Repetition + Rule * Congruency', ...
    };

runAPC;