clear variables; clc;
ridgeLambda = 1;
smoothLambda = 0;
numFolds = 5;
isOverwrite = false;
includeTimeBeforeZero = true;
timePeriods = {'Rule Response'};
model = {...
    'Constant', ...
    'Previous Error + Response Direction', ...
    'Previous Error + Response Direction + Rule Repetition', ...
    'Previous Error + Response Direction + Congruency', ...
    'Previous Error + Response Direction + Rule Repetition + Congruency', ...
    'Previous Error + Response Direction + Rule', ...
    'Previous Error + Response Direction + Rule Repetition + Rule', ...
    'Previous Error + Response Direction + Congruency + Rule', ...
    'Previous Error + Response Direction + Rule Repetition + Congruency + Rule', ...
    'Rule * Previous Error + Response Direction', ...
    'Rule * Previous Error + Response Direction + Rule * Rule Repetition', ...
    'Rule * Previous Error + Response Direction + Rule * Congruency', ...
    'Rule * Previous Error + Response Direction + Rule * Rule Repetition + Rule * Congruency', ...
    };

runGAMfit;