clear variables; clc;
ridgeLambda = 0;
numFolds = 1;
isOverwrite = true;

%% Pre-Test Stimulus
timePeriods = {'Intertrial Interval', 'Fixation', 'Rule Stimulus'};
model = {...
    'Constant', ...
    'Previous Error History', ...
    'Previous Error History + Previous Congruency', ...
    'Rule Repetition + Previous Error History', ...
    'Rule + Previous Error History', ...
    'Rule * Previous Error History', ...
    'Rule * Previous Error History + Rule * Previous Congruency', ...
    'Rule * Rule Repetition + Rule * Previous Error History', ...
    };

for time_ind = 1:length(timePeriods),
    fprintf('\n\t Time Period: %s\n', timePeriods{time_ind});
    for model_ind = 1:length(model)
        GAMcluster(model{model_ind}, timePeriods{time_ind}, ...
            'numFolds', numFolds, 'overwrite', isOverwrite, ...
            'ridgeLambda', ridgeLambda, 'isPrediction', false);
    end
end

%% Post-Test Stimulus
timePeriods = {'Stimulus Response', 'Saccade', 'Reward'};
model = {...
    'Constant', ...
    'Previous Error History + Response Direction', ...
    'Congruency History + Previous Error History + Response Direction', ...
    'Rule Repetition + Previous Error History + Response Direction', ...
    'Previous Error History + Response Direction + Indicator Prep Time', ...
    'Rule + Previous Error History + Response Direction', ...
    'Rule * Previous Error History + Response Direction', ...
    'Rule * Previous Error History + Rule * Congruency History + Response Direction', ...
    'Rule * Rule Repetition + Rule * Previous Error History + Response Direction', ...
    'Rule * Previous Error History + Response Direction + Rule * Indicator Prep Time', ...
    };

for time_ind = 1:length(timePeriods),
    fprintf('\n\t Time Period: %s\n', timePeriods{time_ind});
    for model_ind = 1:length(model)
        fprintf('\n Model: %s\n', model{model_ind});
        GAMcluster(model{model_ind}, timePeriods{time_ind}, ...
            'numFolds', numFolds, 'overwrite', isOverwrite, ...
            'ridgeLambda', ridgeLambda, 'isPrediction', false);
    end
end

%% Post-Test Stimulus - over time
% timePeriods = {'Stimulus Response'};
% model{1} = 's(Rule, Trial Time) + s(Rule Repetition, Trial Time) + s(Previous Error, Trial Time) + s(Congruency History, Trial Time) + s(Response Direction, Trial Time) + s(Indicator Prep Time, Trial Time)';
% model{2} = 'Rule * Rule Repetition + Rule * Previous Error + Rule * Congruency History + Previous Error * Response Direction + Rule * Indicator Prep Time';
% 
% for time_ind = 1:length(timePeriods),
%     fprintf('\n\t Time Period: %s\n', timePeriods{time_ind});
%     for model_ind = 1:length(model)
%         fprintf('\n Model: %s\n', model{model_ind});
%         GAMcluster(model{model_ind}, timePeriods{time_ind}, main_dir, 'numFolds', numFolds, 'overwrite', isOverwrite, 'ridgeLambda', ridgeLambda, 'includeTimeBeforeZero', true);        
%     end
% end
